name: CD

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Many color libraries just need this to be set to any value, but at least
  # one distinguishes color depth, where "3" -> "256-bit color".
  FORCE_COLOR: 3

jobs:
  build:
    name: Container build and push
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
        attestations: write
        id-token: write
    env:
      IMAGE_NAME: "nginx-webdav"
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build image
        run: docker build -f nginx/nginx.dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}" ./nginx

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag image
        id: tag_image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID >> $GITHUB_OUTPUT
          echo VERSION=$VERSION >> $GITHUB_OUTPUT
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION

      - name: Push image
        if: github.event_name == 'release'
        run: docker push $IMAGE_ID:$VERSION
        env:
          IMAGE_ID: ${{ steps.tag_image.outputs.IMAGE_ID }}
          VERSION: ${{ steps.tag_image.outputs.VERSION }}
        